### ISSUE TITLE
Overleaf/online template?

### ISSUE THREAD

**Issue by ArnoutDevos** [rescience-c/template#7]
Hi,

We would like to submit our work on April 10, 2019.

We have now used the [NeurIPS 2018 template](https://nips.cc/Conferences/2018/PaperInformation/StyleFiles) in Overleaf. Do you have (just like the NeurIPS, ICLR, ICML, ... conferences/journals) an Overleaf/other online editor compatible template available?

Thanks!

**Comment by rougier** [comment]
Not yet actually and I'm not sure how to do it. I'll give a look.
@pdebuyl are you familiar with overleaf template ?

**Comment by pdebuyl** [comment]
I never used overleaf but according to a SO reply https://tex.stackexchange.com/a/392909/71116 we can create a sample document formatted "à la" ReScience C and publish it for others to use. overleaf supports user-supplied fonts for xelatex as well https://www.overleaf.com/learn/latex/XeLaTeX#Fonts_in_Overleaf

**Comment by ArnoutDevos** [comment]
> I never used overleaf but according to a SO reply https://tex.stackexchange.com/a/392909/71116 we can create a sample document formatted "à la" ReScience C and publish it for others to use. overleaf supports user-supplied fonts for xelatex as well https://www.overleaf.com/learn/latex/XeLaTeX#Fonts_in_Overleaf

That would be great. Can you make (us) such a template document on Overleaf?

**Comment by rougier** [comment]
Yes, I'm on it actually. By the end of the week it'll be online hopefully.

**Comment by rougier** [comment]
@ArnoutDevos First tentative: https://www.overleaf.com/read/kfrwdmygjyqw
